### ISSUE TITLE
Discography section (blurred BG) is causing an insufferable amount of lag and I hate it

### ISSUE THREAD

**Issue by V3ntus** [V3ntus/music.gladiusso.com#1]
https://github.com/V3ntus/V3ntus.github.io/blob/0acc0f385484f0313af0c61747eb081f150420c6/css/main.css#L293-L303

**Comment by V3ntus** [comment]
Fix:
`main.css:`
```css
* {
    display: none !important;
}
```
